# Generated by Django 3.1.4 on 2020-12-20 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('StudentID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=60)),
                ('Gender', models.CharField(max_length=1)),
                ('Nationality', models.CharField(max_length=30)),
                ('PhoneNumber', models.IntegerField()),
                ('Major', models.CharField(max_length=50)),
                ('BirthofDate', models.DateField()),
                ('GPA', models.FloatField()),
            ],
        ),
    ]
