# Generated by Django 3.1.4 on 2020-12-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationSystem', '0002_auto_20201220_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='StudentID',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
