# Generated by Django 3.1.4 on 2020-12-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RegistrationSystem', '0003_auto_20201220_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Password',
            field=models.CharField(default='', max_length=60),
        ),
    ]
